-- Baseline of the schema as Hibernate (ddl-auto=update) managed it before Flyway was introduced.
-- On the existing production database this is baselined (marked applied, NOT executed); it runs only
-- on a fresh database. Keep it in sync with the JPA entities.

create table catalog_section (
    id    bigint generated by default as identity primary key,
    code  varchar(255) not null unique,
    label varchar(255) not null
);

create table document (
    id                 bigint generated by default as identity primary key,
    created_at         timestamp(6) with time zone not null,
    title              varchar(255),
    doc_type           varchar(255),
    document_number    varchar(255),
    counterparty       varchar(255),
    doc_date           date,
    amount             numeric(38, 2),
    warranty_until     date,
    ocr_text           text,
    section_id         bigint references catalog_section,
    telegram_file_id   varchar(255),
    channel_message_id bigint,
    content_hash       varchar(64),
    file_size_bytes    bigint,
    original_filename  varchar(255),
    backup_status      varchar(32) not null
);

create index idx_document_backup_status on document (backup_status);
create index idx_document_content_hash on document (content_hash);

create table api_usage (
    id            bigint primary key,
    input_tokens  bigint not null,
    output_tokens bigint not null
);
