-- Multi-page documents: a document is a logical unit whose recognized text/fields live on `document`,
-- and each source photo becomes a row in `document_page`. Existing single-file documents are migrated
-- to a single page (page 1). The per-file columns move off `document` onto `document_page`.

create table document_page (
    id                 bigint generated by default as identity primary key,
    document_id        bigint  not null references document on delete cascade,
    page_number        integer not null,
    telegram_file_id   varchar(255),
    channel_message_id bigint,
    content_hash       varchar(64),
    file_size_bytes    bigint,
    original_filename  varchar(255),
    constraint uq_document_page unique (document_id, page_number)
);
create index idx_document_page_document on document_page (document_id);

-- Move each existing document's single file into its page 1.
insert into document_page (document_id, page_number, telegram_file_id, channel_message_id, content_hash,
                           file_size_bytes, original_filename)
select id, 1, telegram_file_id, channel_message_id, content_hash, file_size_bytes, original_filename
from document;

alter table document add column page_count integer not null default 1;

-- content_hash stays on document (now the whole-pack hash; equals the single file's hash for migrated rows).
alter table document
    drop column telegram_file_id,
    drop column channel_message_id,
    drop column file_size_bytes,
    drop column original_filename;
